[package]
name = "zbusd"
version = "0.1.0"
description = "A simple D-Bus bus (broker) implementation"
edition = "2021"

[lib]
name = "zbusd"
path = "src/lib.rs"

[[bin]]
name = "zbusd"
path = "src/bin/zbusd.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { git = "https://gitlab.freedesktop.org/dbus/zbus/", features = ["tokio"], default-features = false }
nix = "0.23.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "signal" ] }
clap = { version = "3.2.6", features = ["derive"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter" , "fmt"], default-features = false }
anyhow = "1.0.58"
# Explicitly depend on serde to enable `rc` feature.
serde = { version = "1.0.140", features = ["rc"] }
futures-util = "0.3.23"
parking_lot = "0.12.1"
enumflags2 = "0.7.0"
