[package]
name = "dbuz"
version = "0.1.0"
authors = ["Zeeshan Ali Khan <zeeshanak@gnome.org>"]
description = "A simple D-Bus bus (broker) implementation"
edition = "2021"
license = "MIT"
readme = "README.md"
rust-version = "1.60"
repository = "https://gitlab.freedesktop.org/zeenix/dbuz/"
keywords = ["D-Bus", "DBus", "IPC"]
categories = ["network-programming"]

[lib]
name = "dbuz"
path = "src/lib.rs"

[[bin]]
name = "dbuz"
path = "src/bin/dbuz.rs"

[dependencies]
zbus = { git = "https://gitlab.freedesktop.org/dbus/zbus/", features = ["tokio"], default-features = false }
#zbus = { version = "3.4.0", features = ["tokio"], default-features = false }
nix = "0.25.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "signal", "tracing" ] }
clap = { version = "4.0.18", features = ["derive"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter" , "fmt"], default-features = false, optional = true }
anyhow = "1.0.58"
# Explicitly depend on serde to enable `rc` feature.
serde = { version = "1.0.140", features = ["rc"] }
futures-util = "0.3.23"
parking_lot = "0.12.1"
enumflags2 = "0.7.0"
ntest = "0.9.0"
console-subscriber = { version = "0.1.8", optional = true }

[dev-dependencies]
fastrand = "1.8.0"

[features]
default = ["tracing-subscriber"]