# Run `cargo test` on windwos, linux and mac
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Add windows-latest when we can handle it
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUST_LOG: "trace"
          RUST_BACKTRACE: "full"
        with:
          command: test
          args: --no-fail-fast
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUST_LOG: "trace"
          RUST_BACKTRACE: "full"
        with:
          command: test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
